version: 2.0
jobs:
  build_gcc_7:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: cmake .. -DBUILD_EXAMPLE=ON
      - run: make
      - run: ./example/example
  build_gcc_latest:
    docker:
      - image: gcc:8
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: cmake .. -DBUILD_EXAMPLE=ON
      - run: make
      - run: ./example/example

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_7
      - build_gcc_8
