version: 2.0
jobs:
  build_gcc_7:
    docker:
      - image: rikorose/gcc-cmake:gcc-7
    steps:
      - checkout
      - run: cmake -H. -Bbuild -DBUILD_EXAMPLE=ON
      - run: cmake --build build
      - run: ./build/example/example
  build_gcc_8:
    docker:
      - image: rikorose/gcc-cmake:gcc-8
    steps:
      - checkout
      - run: cmake -H. -Bbuild -DBUILD_EXAMPLE=ON
      - run: cmake --build build
      - run: ./build/example/example

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_7
      - build_gcc_8
