name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake -H. -Bbuild -DBUILD_EXAMPLE=ON
    - name: cmake build
      run: cmake --build build
    - name: example
      run: ./build/example/example
